"use client";

import React from "react";
import { Modal } from "@/components/ui/Modal";
import { PolicyInsight } from "@/lib/types";
import { PriorityBadge } from "./PriorityBadge";
import { CheckCircle2, Calculator, Users, Quote } from "lucide-react";

interface InsightEvidenceViewerProps {
  insight: PolicyInsight | null;
  isOpen: boolean;
  onClose: () => void;
}

export const InsightEvidenceViewer: React.FC<InsightEvidenceViewerProps> = ({
  insight,
  isOpen,
  onClose,
}) => {
  if (!insight) return null;

  const breakdown = insight.priority_breakdown;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Verifiable Evidence Base: ${insight.id}`}
      subtitle={`${insight.topic} • ${insight.frequency_count} Supporting Submissions`}
      maxWidth="4xl"
    >
      <div className="space-y-6">
        {/* Policy Summary Reminder */}
        <div className="bg-slate-900 text-slate-100 p-4 rounded-lg">
          <div className="flex items-center justify-between gap-2 mb-1">
            <span className="text-[10px] font-mono uppercase text-emerald-400 font-semibold">
              Synthesized Policy Recommendation
            </span>
            <PriorityBadge level={insight.priority_level} score={insight.priority_score} />
          </div>
          <h4 className="text-sm font-bold leading-snug">{insight.title}</h4>
          <p className="text-xs text-slate-300 mt-2 leading-relaxed">
            {insight.suggestion_summary}
          </p>
        </div>

        {/* Explainable Priority Formula Box */}
        {breakdown && (
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg space-y-2 text-xs">
            <div className="flex items-center gap-1.5 font-bold text-slate-900">
              <Calculator className="w-4 h-4 text-emerald-700" />
              <span>Transparent Priority Formulation</span>
            </div>
            <p className="text-slate-700 leading-relaxed font-mono text-[11px]">
              {insight.priority_explanation}
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-slate-200 text-[11px]">
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Severity Component</span>
                <span className="font-bold text-slate-900">+{breakdown.severity_component}</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Stakeholder Diversity</span>
                <span className="font-bold text-slate-900">+{breakdown.stakeholder_diversity_component}</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Submission Volume</span>
                <span className="font-bold text-slate-900">+{breakdown.volume_component}</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Negative Friction</span>
                <span className="font-bold text-slate-900">+{breakdown.negative_friction_component}</span>
              </div>
            </div>
          </div>
        )}

        {/* Evidence Methodology Alert */}
        <div className="p-3 bg-emerald-50/70 border border-emerald-200/80 rounded-lg text-xs text-emerald-950 flex items-start gap-2.5">
          <CheckCircle2 className="w-4 h-4 text-emerald-700 mt-0.5 flex-shrink-0" />
          <div>
            <span className="font-semibold">Evidence Traceability: </span>
            Every policy insight generated by PolicyLens is directly tethered to verifiable public consultation submissions. Below are the exact verbatim excerpts from stakeholders that substantiate this recommendation.
          </div>
        </div>

        {/* Verbatim Supporting Quotes List */}
        <div className="space-y-4">
          <div className="flex items-center justify-between text-xs font-semibold text-slate-700 uppercase tracking-wider">
            <span>Verbatim Stakeholder Citations ({insight.evidence_quotes.length})</span>
            <span className="font-mono text-slate-400">Total Supporting IDs: {insight.supporting_comment_ids.length}</span>
          </div>

          <div className="space-y-3">
            {insight.evidence_quotes.map((eq, idx) => (
              <div
                key={idx}
                className="bg-white border border-slate-200 rounded-lg p-4 space-y-3 shadow-xs"
              >
                <div className="flex items-center justify-between text-xs border-b border-slate-100 pb-2">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                      {eq.comment_id}
                    </span>
                    <span className="font-semibold text-slate-900">
                      {eq.organization_or_individual || eq.stakeholder_type}
                    </span>
                    <span className="text-slate-400">({eq.stakeholder_type})</span>
                  </div>
                  {eq.section && (
                    <span className="text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded text-[11px] font-medium">
                      {eq.section}
                    </span>
                  )}
                </div>

                <div className="text-xs sm:text-sm text-slate-800 font-serif leading-relaxed italic bg-slate-50 p-3 rounded border border-slate-100">
                  "{eq.verbatim_text}"
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Modal>
  );
};
