"use client";

import React from "react";
import { Modal } from "@/components/ui/Modal";
import { PolicyInsight } from "@/lib/types";
import { PriorityBadge } from "./PriorityBadge";
import { CheckCircle2, Calculator, Users, Quote, AlertTriangle, Lightbulb } from "lucide-react";

interface InsightEvidenceViewerProps {
  insight: PolicyInsight | null;
  isOpen: boolean;
  onClose: () => void;
}

export const InsightEvidenceViewer: React.FC<InsightEvidenceViewerProps> = ({
  insight,
  isOpen,
  onClose,
}) => {
  if (!insight) return null;

  const factors = insight.priority_factors;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Verifiable Evidence Base: ${insight.id}`}
      subtitle={`${insight.topic} • ${insight.frequency} Submissions (${insight.frequency_percentage}%)`}
      maxWidth="4xl"
    >
      <div className="space-y-6">
        {/* Policy Summary Reminder */}
        <div className="bg-slate-900 text-slate-100 p-4 rounded-lg">
          <div className="flex items-center justify-between gap-2 mb-1">
            <span className="text-[10px] font-mono uppercase text-emerald-400 font-semibold">
              Synthesized Policy Recommendation
            </span>
            <PriorityBadge level={insight.priority_level} score={insight.priority_score} />
          </div>
          <h4 className="text-sm font-bold leading-snug">{insight.title}</h4>
          <p className="text-xs text-slate-300 mt-2 leading-relaxed">
            {insight.suggestion}
          </p>
        </div>

        {/* Explainable Priority Formula Box */}
        {factors && (
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg space-y-2 text-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5 font-bold text-slate-900">
                <Calculator className="w-4 h-4 text-emerald-700" />
                <span>Transparent Priority Formulation</span>
              </div>
              <span className="font-mono text-emerald-800 font-bold">{insight.priority_score} / 100 [{insight.priority_level}]</span>
            </div>
            <p className="text-slate-700 leading-relaxed font-mono text-[11px]">
              {insight.priority_explanation}
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-slate-200 text-[11px]">
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Severity Score</span>
                <span className="font-bold text-slate-900">+{factors.severity_score} pts</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Stakeholder Diversity</span>
                <span className="font-bold text-slate-900">+{factors.stakeholder_diversity_score} pts</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Frequency Share</span>
                <span className="font-bold text-slate-900">+{factors.frequency_score} pts</span>
              </div>
              <div className="p-2 bg-white rounded border border-slate-200">
                <span className="text-slate-400 block text-[10px]">Sentiment Friction</span>
                <span className="font-bold text-slate-900">+{factors.sentiment_intensity_score} pts</span>
              </div>
            </div>
          </div>
        )}

        {/* Evidence Methodology Alert */}
        <div className="p-3 bg-emerald-50/70 border border-emerald-200/80 rounded-lg text-xs text-emerald-950 flex items-start gap-2.5">
          <CheckCircle2 className="w-4 h-4 text-emerald-700 mt-0.5 flex-shrink-0" />
          <div>
            <span className="font-semibold">Evidence Traceability Guarantee: </span>
            Every policy insight generated by PolicyLens is directly anchored in verifiable stakeholder comments. Below are the exact verbatim quotes and extracted components from the consultation corpus.
          </div>
        </div>

        {/* Verbatim Supporting Quotes List */}
        <div className="space-y-4">
          <div className="flex items-center justify-between text-xs font-semibold text-slate-700 uppercase tracking-wider">
            <span>Verbatim Supporting Submissions ({insight.supporting_evidence.length})</span>
            <span className="font-mono text-slate-400">Total Supporting IDs: {insight.supporting_comment_ids.length}</span>
          </div>

          <div className="space-y-3">
            {insight.supporting_evidence.map((eq, idx) => (
              <div
                key={idx}
                className="bg-white border border-slate-200 rounded-lg p-4 space-y-3 shadow-xs"
              >
                <div className="flex items-center justify-between text-xs border-b border-slate-100 pb-2">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                      {eq.comment_id}
                    </span>
                    <span className="font-semibold text-slate-900">
                      {eq.organization_or_individual || eq.stakeholder_type}
                    </span>
                    <span className="text-slate-400">({eq.stakeholder_type})</span>
                  </div>
                  {eq.section && (
                    <span className="text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded text-[11px] font-medium">
                      {eq.section}
                    </span>
                  )}
                </div>

                <div className="text-xs sm:text-sm text-slate-800 font-serif leading-relaxed italic bg-slate-50 p-3 rounded border border-slate-100">
                  "{eq.verbatim_text}"
                </div>

                {/* Granular Extractions from this comment */}
                {(eq.extracted_concerns?.length > 0 || eq.extracted_suggestions?.length > 0) && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] pt-1">
                    {eq.extracted_concerns?.length > 0 && (
                      <div className="p-2 bg-rose-50/50 rounded border border-rose-100 text-rose-900">
                        <span className="font-bold flex items-center gap-1 mb-0.5">
                          <AlertTriangle className="w-3 h-3 text-rose-600" />
                          Extracted Friction:
                        </span>
                        <span>{eq.extracted_concerns[0]}</span>
                      </div>
                    )}
                    {eq.extracted_suggestions?.length > 0 && (
                      <div className="p-2 bg-emerald-50/50 rounded border border-emerald-100 text-emerald-900">
                        <span className="font-bold flex items-center gap-1 mb-0.5">
                          <Lightbulb className="w-3 h-3 text-emerald-600" />
                          Extracted Proposal:
                        </span>
                        <span>{eq.extracted_suggestions[0]}</span>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </Modal>
  );
};
